title: '#BarrysLounge #UpTheMarket'
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.5
  brandStrength: 0.5
  rhythmicContrast: 0.4169393111951649
  brandColors:
    - '#171695'
    - '#ffffff'
    - '#cd7e7a'
    - '#a8262f'
    - '#97b667'
  lightness: 0.5
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: UA-72330144-1
  facebook: null
name: '#BarrysLounge'
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.2861587300430983
layout_spectrum: 0.4283154
