name: '#BarrysLounge'
favicon: null
layout_spectrum: 0.4987910492345691
typography_spectrum: 0.28615873004309833
title: '#BarrysLounge #UpTheMarket'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#171695'
    - '#ffffff'
    - '#cd7e7a'
    - '#a8262f'
    - '#97b667'
  brandStrength: 0.9227824071422219
  lightness: 0.9522669473662972
  saturation: 0.8174440532457083
  rhythmicContrast: 0.4169393111951649
purpose: []
