name: '#BarrysLounge '
favicon: null
layout_spectrum: 0.4283154
typography_spectrum: 0.2861587300430983
title: '#BarrysLounge'
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-72330144-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#171695'
    - '#ffffff'
    - '#cd7e7a'
    - '#a8262f'
    - '#97b667'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.4169393111951649
purpose: []
