typography_spectrum: 0.2861587300430983
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 0.4283154
title: '#BarrysLounge'
cta:
  bucket: null
  version: null
  domain: null
color:
  saturation: 0.25
  brandStrength: 0.25
  rhythmicContrast: 0.25
  brandColors:
    - '#171695'
    - '#ffffff'
    - '#cd7e7a'
    - '#a8262f'
    - '#97b667'
  lightness: 0.5
purpose: []
favicon: null
analytics:
  twitter: null
  google: UA-72330144-1
  facebook: null
name: '#BarrysLounge '
